version: 2.1

orbs:
  node: circleci/node@4.1.1

jobs:
  publish:
    executor: &node-lts
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages
      - run: &setup-private-npm
          name: Set npm credentials for publishing
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
      - run:
          name: Publish on npm
          command: npm run publish-please

  test-custom-ts-example:
    executor: *node-lts
    steps:
      - checkout
      - node/install-packages:
          app-dir: examples/custom-ts
      - run:
          name: Deploy and test custom app
          command: npm run testexamples-custom-ts

workflows:
  version: 2

  test-and-publish:
    jobs:
      - node/test:
          version: lts
          filters:
            tags:
              only: /.*/
      
      - publish:
          context: manwaring-npm
          requires: [node/test]
          filters: &only-versioned-tags
            branches:
              ignore: /.*/
            tags:
              only: /v.*/

      - test-custom-ts-example:
          context: aws-manwaring
          requires: [publish]
          filters: *only-versioned-tags
