## Circle CI configuration, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  publish:
    executor: &node-lts
      name: node/default
      tag: lts
    steps:
      - checkout
      - node/install-packages
      - run: &setup-private-npm
          name: Set npm credentials for publishing
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
      - run:
          name: Publish on npm
          command: npm run publish-please

  test-default-ts-example:
    executor: *node-lts
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy and test default example app
          command: npm run testexamples-default-ts

  test-default-js-example:
    executor: *node-lts
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy and test default example app
          command: npm run testexamples-default-js

  test-custom-ts-example:
    executor: *node-lts
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy and test custom app
          command: npm run testexamples-custom-ts

workflows:
  version: 2

  test-and-publish:
    jobs:
      - node/test:
          version: lts
          filters:
            tags:
              only: /.*/
      # TODO add a dry-run step to non-tagged changes
      # - publish-dry-run:
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /.*/
      - publish:
          context: manwaring-npm
          requires: [node/test]
          filters: &only-versioned-tags
            branches:
              ignore: /.*/
            tags:
              only: /v.*/

      - test-default-ts-example:
          context: aws-manwaring
          requires: [publish]
          filters: *only-versioned-tags

      - test-custom-ts-example:
          context: aws-manwaring
          requires: [publish]
          filters: *only-versioned-tags

      - test-default-js-example:
          context: aws-manwaring
          requires: [publish]
          filters: *only-versioned-tags
