service: test-helper-custom-ts

plugins:
  - serverless-webpack
  - serverless-plugin-test-helper

provider:
  name: aws
  stage: example
  runtime: nodejs12.x

custom:
  testHelper:
    path: .stack-outputs.yml

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: post
          path: hello
